### ISSUE TITLE
Ad Mob with plugin Crashes

### ISSUE THREAD

**Issue by IllyasKhan** [mopsicus/native-android-camera-unity#1]
when I make an object of admob using this plugin, after click the camera and press okay button the game crash please help me to solve this problem. assp please.

**Comment by mopsicus** [comment]
Maybe you give some additional info about problem? Console log e.g.?

**Comment by IllyasKhan** [comment]
thanks for replay:
this issue come only On Samsung c5 Pro Android version 6.0.1.
I have checked it all other devices bus the crash issue come's only on mention device More over when I comment RequestBanner(); RequestInterstitial(); in GoogleMobileAdsDemoScript
in that case app not crash. help Please

**Comment by mopsicus** [comment]
So, how does it refer with my plugin?
I guess, problem in Admob plugin

**Comment by IllyasKhan** [comment]
sorry I am not asking that its the problem with the plugin I need help from you if it possible !!

**Comment by IllyasKhan** [comment]
sorry I just realise that it could bad impact on your profile If you say I
can delete that all comment as well !!
I am actually asking the trouble that I am facing if you could help or you
face that type of problem in any time so you can share and help me :(


*Muhammad Illyas KhanBaca Baca Game (Team Lead)*

C: 0315-2149017
E: illyasicaw@gmail.com <marsalanbhatti@gmail.com>

**Comment by mopsicus** [comment]
Mail me to mail@mopsicus.ru with crash log, and I'll try to help you
